apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: pavani-ns
spec:
  selector:
    app: httpbin-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
